
#imports
import time
import os

# Functions

def  cl():
    os.system("clear")

#STARTTT HERER

cl()
time.sleep(1)
print("...")
time.sleep(3)
cl()
print("Loading...")
time.sleep(3)
cl()
print("oh ... hello there!")
time.sleep(3)
print("\n")
print("You will have to get a paper sheet and a pencil for this.")
time.sleep(2)
print("...")
time.sleep(2)
print("I'll wait 20 secondsss...")
time.sleep(2)
cl()
print("1")
time.sleep(1)
cl()

print("2")
time.sleep(1)
cl()

print("3")
time.sleep(1)
cl()
print("4")
time.sleep(1)
cl()
print("5")
time.sleep(1)
cl()
print("6")
time.sleep(1)
cl()
print("7")
time.sleep(1)
cl()
print("8")
time.sleep(1)
cl()
print("9")
time.sleep(1)
cl()
print("10")
time.sleep(1)
cl()
print("11")
time.sleep(1)
cl()
print("12")
time.sleep(1)
cl()
print("13")
time.sleep(1)
cl()
print("14")
time.sleep(1)
cl()
print("15")
time.sleep(1)
cl()
print("16")
time.sleep(1)
cl()
print("17")
time.sleep(1)
cl()
print("18")
time.sleep(1)
cl()
print("19")
time.sleep(1)
cl()
print("20")
time.sleep(2)
cl()
print("Okayyy... \n I hope you brought it now. \n You HAVE to write everything down what is written here")
time.sleep(3)
cl()
time.sleep(3)
print("Hie thee hence, anon depart;")
time.sleep(5)
print("\n")
print("Beneath the iron hearth's grim maw descend,")
time.sleep(5)
print("\n")
time.sleep(5)
print("Where shadowed silence keeps her jealous watch.")
print("\n")
time.sleep(5)
print("In covert nook, from mortal gaze withdrawn,")
print("\n")
time.sleep(5)
print("There lurketh that which seeketh thy discovery.")
print("\n")
time.sleep(5)
print("Pursue the veiled whisper of concealment,")
print("\n")
time.sleep(5)
print("And, by Fortune's lantern dimly borne,")
print("\n")
time.sleep(5)
print("Thou shalt espy it.")
time.sleep(8)
cl()
print("Did you write that down?")
time.sleep(2)
cl()
print("This message will self-destruct in...")
time.sleep(1)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)
print("Self destructing...")
time.sleep(3)
os.system("rm -f main.py")
